[package]
name = "icpc_scoreboard"
version = "0.1.0"
edition = "2021"

[dependencies]
quarve = { version = "0.1.0" }
reqwest = "0.12.12"
scraper = "0.22.0"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }

